export type ThemeId = "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10";

export interface ThemeConfig {
  id: ThemeId;
  name: string;
  // Light vs dark base
  isDark: boolean;
  // Results table: light or dark
  resultsTableDark: boolean;
  // CSS variable overrides
  cssVars: Record<string, string>;
}

export const THEME_NAMES: Record<ThemeId, string> = {
  "1": "Scroll",
  "2": "Chronicle",
  "3": "Slides",
  "4": "Command",
  "5": "Press",
  "6": "Kanban",
  "7": "Manifesto",
  "8": "Magazine",
  "9": "Data",
  "10": "Terminal",
};

export const themes: ThemeConfig[] = [
  {
    id: "1",
    name: "Horizon",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#1672FD",
      "--color-bg": "#FFFFFF",
      "--color-bg-alt": "#E8F1FF",
      "--color-surface": "#FFFFFF",
      "--color-text": "#353535",
      "--color-text-muted": "#858D99",
      "--color-accent": "#6EE0AA",
      "--color-border": "#EAEEEE",
      "--color-results-bg": "#F9F9F9",
      "--color-results-accent": "#6EE0AA",
    },
  },
  {
    id: "2",
    name: "Midnight",
    isDark: true,
    resultsTableDark: true,
    cssVars: {
      "--color-primary": "#4A9DFF",
      "--color-bg": "#1A1A2E",
      "--color-bg-alt": "#252540",
      "--color-surface": "#252540",
      "--color-text": "#E8E8EC",
      "--color-text-muted": "#9C9FA1",
      "--color-accent": "#6EE0AA",
      "--color-border": "#3A3A5C",
      "--color-results-bg": "#252540",
      "--color-results-accent": "#6EE0AA",
    },
  },
  {
    id: "3",
    name: "Command",
    isDark: true,
    resultsTableDark: true,
    cssVars: {
      "--color-primary": "#6EE0AA",
      "--color-bg": "#0D1F17",
      "--color-bg-alt": "#1A2F24",
      "--color-surface": "#1A2F24",
      "--color-text": "#E8FCEF",
      "--color-text-muted": "#6EE0AA",
      "--color-accent": "#6EE0AA",
      "--color-border": "#2E4A3A",
      "--color-results-bg": "#1A2F24",
      "--color-results-accent": "#6EE0AA",
    },
  },
  {
    id: "4",
    name: "Breath",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#858D99",
      "--color-bg": "#FFFFFF",
      "--color-bg-alt": "#FFFFFF",
      "--color-surface": "#FFFFFF",
      "--color-text": "#353535",
      "--color-text-muted": "#9C9FA1",
      "--color-accent": "#05C6C6",
      "--color-border": "#F2F2F2",
      "--color-results-bg": "#FAFAFA",
      "--color-results-accent": "#05C6C6",
    },
  },
  {
    id: "5",
    name: "Punch",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#1672FD",
      "--color-bg": "#FFFFFF",
      "--color-bg-alt": "#F4F4F4",
      "--color-surface": "#FFFFFF",
      "--color-text": "#000000",
      "--color-text-muted": "#444444",
      "--color-accent": "#FD7168",
      "--color-border": "#000000",
      "--color-results-bg": "#F4F4F4",
      "--color-results-accent": "#FD7168",
    },
  },
  {
    id: "6",
    name: "Mist",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#986BFC",
      "--color-bg": "#FAEBFF",
      "--color-bg-alt": "#F5E0FF",
      "--color-surface": "#FFFFFF",
      "--color-text": "#444444",
      "--color-text-muted": "#6B6B80",
      "--color-accent": "#986BFC",
      "--color-border": "#E8D4FF",
      "--color-results-bg": "#FAEBFF",
      "--color-results-accent": "#986BFC",
    },
  },
  {
    id: "7",
    name: "Monochrome",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#1672FD",
      "--color-bg": "#FFFFFF",
      "--color-bg-alt": "#F2F2F2",
      "--color-surface": "#FFFFFF",
      "--color-text": "#000000",
      "--color-text-muted": "#666666",
      "--color-accent": "#000000",
      "--color-border": "#000000",
      "--color-results-bg": "#000000",
      "--color-results-accent": "#FFFFFF",
    },
  },
  {
    id: "8",
    name: "Ember",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#FD7168",
      "--color-bg": "#FFF5F4",
      "--color-bg-alt": "#FFE9E9",
      "--color-surface": "#FFFFFF",
      "--color-text": "#353535",
      "--color-text-muted": "#858D99",
      "--color-accent": "#FFCB3E",
      "--color-border": "#F5DDD8",
      "--color-results-bg": "#FCF6E8",
      "--color-results-accent": "#FD7168",
    },
  },
  {
    id: "9",
    name: "Reef",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#05C6C6",
      "--color-bg": "#E3FCEF",
      "--color-bg-alt": "#DFF4F4",
      "--color-surface": "#FFFFFF",
      "--color-text": "#1A2F24",
      "--color-text-muted": "#444444",
      "--color-accent": "#05C6C6",
      "--color-border": "#B8E6E6",
      "--color-results-bg": "#DFF4F4",
      "--color-results-accent": "#05C6C6",
    },
  },
  {
    id: "10",
    name: "Broadsheet",
    isDark: false,
    resultsTableDark: false,
    cssVars: {
      "--color-primary": "#353535",
      "--color-bg": "#FFFFFF",
      "--color-bg-alt": "#F9F9F9",
      "--color-surface": "#FFFFFF",
      "--color-text": "#000000",
      "--color-text-muted": "#444444",
      "--color-accent": "#1E59AF",
      "--color-border": "#E0DDDA",
      "--color-results-bg": "#F2F2F2",
      "--color-results-accent": "#1E59AF",
    },
  },
];
